[cpu]
[[cpu.conda]]
installer = "conda"
flags = ["pytorch", "torchvision", "torchaudio", "cpuonly", "-c", "pytorch"]
platform = "cpu"
version = "latest"

[cpu.conda.packages]

[[cpu.conda]]
installer = "conda"
flags = ["pytorch", "torchvision", "torchaudio", "cpuonly", "-c", "pytorch"]
platform = "cpu"
version = "latest"

[cpu.conda.packages]

[[cpu.conda]]
installer = "conda"
flags = ["cpuonly", "-c", "pytorch"]
platform = "cpu"
version = "latest"

[cpu.conda.packages]
pytorch = "2.0.0"
torchvision = "0.15.0"
torchaudio = "2.0.0"

[[cpu.conda]]
installer = "conda"
flags = ["cpuonly", "-c", "pytorch"]
version = "1.13.1"
platform = "cpu"

[cpu.conda.packages]
pytorch = "1.13.1"
torchvision = "0.14.1"
torchaudio = "0.13.1"

[[cpu.conda]]
installer = "conda"
flags = ["cpuonly", "-c", "pytorch"]
version = "1.13.0"
platform = "cpu"

[cpu.conda.packages]
pytorch = "1.13.0"
torchvision = "0.14.0"
torchaudio = "0.13.0"

[[cpu.conda]]
installer = "conda"
flags = ["cpuonly", "-c", "pytorch"]
version = "1.12.1"
platform = "cpu"

[cpu.conda.packages]
pytorch = "1.12.1"
torchvision = "0.13.1"
torchaudio = "0.12.1"

[[cpu.conda]]
installer = "conda"
flags = ["cpuonly", "-c", "pytorch"]
version = "1.12.0"
platform = "cpu"

[cpu.conda.packages]
pytorch = "1.12.0"
torchvision = "0.13.0"
torchaudio = "0.12.0"

[[cpu.conda]]
installer = "conda"
flags = ["cpuonly", "-c", "pytorch"]
version = "1.11.0"
platform = "cpu"

[cpu.conda.packages]
pytorch = "1.11.0"
torchvision = "0.12.0"
torchaudio = "0.11.0"

[[cpu.pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/cpu",
]
platform = "cpu"
version = "latest"

[cpu.pip.packages]

[[cpu.pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/cpu",
]
platform = "cpu"
version = "latest"

[cpu.pip.packages]

[[cpu.pip]]
installer = "pip"
flags = ["--index-url", "https://download.pytorch.org/whl/cpu"]
version = "2.0.0"
platform = "cpu"

[cpu.pip.packages]
torch = "2.0.0+cpu"
torchvision = "0.15.1"
torchaudio = "2.0.1"

[[cpu.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cpu"]
version = "1.13.1"
platform = "cpu"

[cpu.pip.packages]
torch = "1.13.1+cpu"
torchvision = "0.14.1+cpu"
torchaudio = "0.13.1"

[[cpu.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cpu"]
version = "1.13.0"
platform = "cpu"

[cpu.pip.packages]
torch = "1.13.0+cpu"
torchvision = "0.14.0+cpu"
torchaudio = "0.13.0"

[[cpu.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cpu"]
version = "1.12.1"
platform = "cpu"

[cpu.pip.packages]
torch = "1.12.1+cpu"
torchvision = "0.13.1+cpu"
torchaudio = "0.12.1"

[[cpu.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cpu"]
version = "1.12.0"
platform = "cpu"

[cpu.pip.packages]
torch = "1.12.0+cpu"
torchvision = "0.13.0+cpu"
torchaudio = "0.12.0"

[[cpu.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pyto"]
version = "1.11.0"
platform = "cpu"

[cpu.pip.packages]
torch = "1.11.0+cpu"
torchvision = "0.12.0+cpu"
torchaudio = "0.11.0"

[cu102]
[[cu102.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.12.1"
platform = "cu102"

[cu102.conda.packages]
pytorch = "1.12.1"
torchvision = "0.13.1"
torchaudio = "0.12.1"
cudatoolkit = "10.2"

[[cu102.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.12.0"
platform = "cu102"

[cu102.conda.packages]
pytorch = "1.12.0"
torchvision = "0.13.0"
torchaudio = "0.12.0"
cudatoolkit = "10.2"

[[cu102.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.11.0"
platform = "cu102"

[cu102.conda.packages]
pytorch = "1.11.0"
torchvision = "0.12.0"
torchaudio = "0.11.0"
cudatoolkit = "10.2"

[[cu102.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu102"]
version = "1.12.1"
platform = "cu102"

[cu102.pip.packages]
torch = "1.12.1+cu102"
torchvision = "0.13.1+cu102"
torchaudio = "0.12.1"

[[cu102.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu102"]
version = "1.12.0"
platform = "cu102"

[cu102.pip.packages]
torch = "1.12.0+cu102"
torchvision = "0.13.0+cu102"
torchaudio = "0.12.0"

[[cu102.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu102"]
version = "1.11.0"
platform = "cu102"

[cu102.pip.packages]
torch = "1.11.0+cu102"
torchvision = "0.12.0+cu102"
torchaudio = "0.11.0"

[cu113]
[[cu113.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.12.1"
platform = "cu113"

[cu113.conda.packages]
pytorch = "1.12.1"
torchvision = "0.13.1"
torchaudio = "0.12.1"
cudatoolkit = "11.3"

[[cu113.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.12.0"
platform = "cu113"

[cu113.conda.packages]
pytorch = "1.12.0"
torchvision = "0.13.0"
torchaudio = "0.12.0"
cudatoolkit = "11.3"

[[cu113.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.11.0"
platform = "cu113"

[cu113.conda.packages]
pytorch = "1.11.0"
torchvision = "0.12.0"
torchaudio = "0.11.0"
cudatoolkit = "11.3"

[[cu113.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu113"]
version = "1.12.1"
platform = "cu113"

[cu113.pip.packages]
torch = "1.12.1+cu113"
torchvision = "0.13.1+cu113"
torchaudio = "0.12.1"

[[cu113.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu113"]
version = "1.12.0"
platform = "cu113"

[cu113.pip.packages]
torch = "1.12.0+cu113"
torchvision = "0.13.0+cu113"
torchaudio = "0.12.0"

[[cu113.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu113"]
version = "1.11.0"
platform = "cu113"

[cu113.pip.packages]
torch = "1.11.0+cu113"
torchvision = "0.12.0+cu113"
torchaudio = "0.11.0"

[cu116]
[[cu116.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "nvidia"]
version = "1.13.1"
platform = "cu116"

[cu116.conda.packages]
pytorch = "1.13.1"
torchvision = "0.14.1"
torchaudio = "0.13.1"
pytorch-cuda = "11.6"

[[cu116.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "nvidia"]
version = "1.13.0"
platform = "cu116"

[cu116.conda.packages]
pytorch = "1.13.0"
torchvision = "0.14.0"
torchaudio = "0.13.0"
pytorch-cuda = "11.6"

[[cu116.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "conda-forge"]
version = "1.12.1"
platform = "cu116"

[cu116.conda.packages]
pytorch = "1.12.1"
torchvision = "0.13.1"
torchaudio = "0.12.1"
cudatoolkit = "11.6"

[[cu116.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "conda-forge"]
version = "1.12.0"
platform = "cu116"

[cu116.conda.packages]
pytorch = "1.12.0"
torchvision = "0.13.0"
torchaudio = "0.12.0"
cudatoolkit = "11.6"

[[cu116.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu116"]
version = "1.13.1"
platform = "cu116"

[cu116.pip.packages]
torch = "1.13.1+cu116"
torchvision = "0.14.1+cu116"
torchaudio = "0.13.1"

[[cu116.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu116"]
version = "1.13.0"
platform = "cu116"

[cu116.pip.packages]
torch = "1.13.0+cu116"
torchvision = "0.14.0+cu116"
torchaudio = "0.13.0"

[[cu116.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu116"]
version = "1.12.1"
platform = "cu116"

[cu116.pip.packages]
torch = "1.12.1+cu116"
torchvision = "0.13.1+cu116"
torchaudio = "0.12.1"

[[cu116.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu116"]
version = "1.12.0"
platform = "cu116"

[cu116.pip.packages]
torch = "1.12.0+cu116"
torchvision = "0.13.0+cu116"
torchaudio = "0.12.0"

[cu117]
[[cu117.conda]]
installer = "conda"
flags = [
  "pytorch",
  "torchvision",
  "torchaudio",
  "-c",
  "pytorch",
  "-c",
  "nvidia",
]
platform = "cu117"
version = "latest"

[cu117.conda.packages]
pytorch-cuda = "11.7"

[[cu117.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "nvidia"]
platform = "cu117"
version = "latest"

[cu117.conda.packages]
pytorch = "2.0.0"
torchvision = "0.15.0"
torchaudio = "2.0.0"
pytorch-cuda = "11.7"

[[cu117.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "nvidia"]
version = "1.13.1"
platform = "cu117"

[cu117.conda.packages]
pytorch = "1.13.1"
torchvision = "0.14.1"
torchaudio = "0.13.1"
pytorch-cuda = "11.7"

[[cu117.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "nvidia"]
version = "1.13.0"
platform = "cu117"

[cu117.conda.packages]
pytorch = "1.13.0"
torchvision = "0.14.0"
torchaudio = "0.13.0"
pytorch-cuda = "11.7"

[[cu117.pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/cu117",
]
platform = "cu117"
version = "latest"

[cu117.pip.packages]

[[cu117.pip]]
installer = "pip"
flags = ["--index-url", "https://download.pytorch.org/whl/cu117"]
version = "2.0.0"
platform = "cu117"

[cu117.pip.packages]
torch = "2.0.0+cu117"
torchvision = "0.15.1"
torchaudio = "2.0.1"

[[cu117.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu117"]
version = "1.13.1"
platform = "cu117"

[cu117.pip.packages]
torch = "1.13.1+cu117"
torchvision = "0.14.1+cu117"
torchaudio = "0.13.1"

[[cu117.pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/cu117"]
version = "1.13.0"
platform = "cu117"

[cu117.pip.packages]
torch = "1.13.0+cu117"
torchvision = "0.14.0+cu117"
torchaudio = "0.13.0"

[cu118]
[[cu118.conda]]
installer = "conda"
flags = [
  "pytorch",
  "torchvision",
  "torchaudio",
  "-c",
  "pytorch",
  "-c",
  "nvidia",
]
platform = "cu118"
version = "latest"

[cu118.conda.packages]
pytorch-cuda = "11.8"

[[cu118.conda]]
installer = "conda"
flags = [
  "pytorch",
  "torchvision",
  "torchaudio",
  "-c",
  "pytorch",
  "-c",
  "nvidia",
]
platform = "cu118"
version = "latest"

[cu118.conda.packages]
pytorch-cuda = "11.8"

[[cu118.conda]]
installer = "conda"
flags = ["-c", "pytorch", "-c", "nvidia"]
platform = "cu118"
version = "latest"

[cu118.conda.packages]
pytorch = "2.0.0"
torchvision = "0.15.0"
torchaudio = "2.0.0"
pytorch-cuda = "11.8"

[[cu118.pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/cu118",
]
platform = "cu118"
version = "latest"

[cu118.pip.packages]

[[cu118.pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/cu118",
]
platform = "cu118"
version = "latest"

[cu118.pip.packages]

[[cu118.pip]]
installer = "pip"
flags = ["--index-url", "https://download.pytorch.org/whl/cu118"]
version = "2.0.0"
platform = "cu118"

[cu118.pip.packages]
torch = "2.0.0+cu118"
torchvision = "0.15.1"
torchaudio = "2.0.1"

[cu121]
[[cu121.conda]]
installer = "conda"
flags = [
  "pytorch",
  "torchvision",
  "torchaudio",
  "-c",
  "pytorch",
  "-c",
  "nvidia",
]
platform = "cu121"
version = "latest"

[cu121.conda.packages]
pytorch-cuda = "12.1"

[[cu121.pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/cu121",
]
platform = "cu121"
version = "latest"

[cu121.pip.packages]

[macOS]
[[macOS.conda]]
installer = "conda"
flags = ["pytorch::pytorch", "torchvision", "torchaudio", "-c", "pytorch"]
platform = "macOS"
version = "latest"

[macOS.conda.packages]

[[macOS.conda]]
installer = "conda"
flags = ["pytorch", "torchvision", "torchaudio", "-c", "pytorch"]
platform = "macOS"
version = "latest"

[macOS.conda.packages]

[[macOS.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
platform = "macOS"
version = "latest"

[macOS.conda.packages]
pytorch = "2.0.0"
torchvision = "0.15.0"
torchaudio = "2.0.0"

[[macOS.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.13.1"
platform = "macOS"

[macOS.conda.packages]
pytorch = "1.13.1"
torchvision = "0.14.1"
torchaudio = "0.13.1"

[[macOS.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.13.0"
platform = "macOS"

[macOS.conda.packages]
pytorch = "1.13.0"
torchvision = "0.14.0"
torchaudio = "0.13.0"

[[macOS.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.12.1"
platform = "macOS"

[macOS.conda.packages]
pytorch = "1.12.1"
torchvision = "0.13.1"
torchaudio = "0.12.1"

[[macOS.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.12.0"
platform = "macOS"

[macOS.conda.packages]
pytorch = "1.12.0"
torchvision = "0.13.0"
torchaudio = "0.12.0"

[[macOS.conda]]
installer = "conda"
flags = ["-c", "pytorch"]
version = "1.11.0"
platform = "macOS"

[macOS.conda.packages]
pytorch = "1.11.0"
torchvision = "0.12.0"
torchaudio = "0.11.0"

[[macOS.pip]]
installer = "pip"
flags = ["torch", "torchvision", "torchaudio"]
platform = "macOS"
version = "latest"

[macOS.pip.packages]

[[macOS.pip]]
installer = "pip"
flags = ["torch", "torchvision", "torchaudio"]
platform = "macOS"
version = "latest"

[macOS.pip.packages]

[[macOS.pip]]
installer = "pip"
flags = []
version = "2.0.0"
platform = "macOS"

[macOS.pip.packages]
torch = "2.0.0"
torchvision = "0.15.1"
torchaudio = "2.0.1"

[[macOS.pip]]
installer = "pip"
flags = []
version = "1.13.1"
platform = "macOS"

[macOS.pip.packages]
torch = "1.13.1"
torchvision = "0.14.1"
torchaudio = "0.13.1"

[[macOS.pip]]
installer = "pip"
flags = []
version = "1.13.0"
platform = "macOS"

[macOS.pip.packages]
torch = "1.13.0"
torchvision = "0.14.0"
torchaudio = "0.13.0"

[[macOS.pip]]
installer = "pip"
flags = []
version = "1.12.1"
platform = "macOS"

[macOS.pip.packages]
torch = "1.12.1"
torchvision = "0.13.1"
torchaudio = "0.12.1"

[[macOS.pip]]
installer = "pip"
flags = []
version = "1.12.0"
platform = "macOS"

[macOS.pip.packages]
torch = "1.12.0"
torchvision = "0.13.0"
torchaudio = "0.12.0"

[[macOS.pip]]
installer = "pip"
flags = []
version = "1.11.0"
platform = "macOS"

[macOS.pip.packages]
torch = "1.11.0"
torchvision = "0.12.0"
torchaudio = "0.11.0"

[["rocm4.5.2".pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/rocm4.5.2"]
version = "1.11.0"
platform = "rocm4.5.2"

["rocm4.5.2".pip.packages]
torch = "1.11.0+rocm4.5.2"
torchvision = "0.12.0+rocm4.5.2"
torchaudio = "0.11.0"

[["rocm5.1.1".pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/rocm5.1.1"]
version = "1.12.1"
platform = "rocm5.1.1"

["rocm5.1.1".pip.packages]
torch = "1.12.1+rocm5.1.1"
torchvision = "0.13.1+rocm5.1.1"
torchaudio = "0.12.1"

[["rocm5.1.1".pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/rocm5.1.1"]
version = "1.12.0"
platform = "rocm5.1.1"

["rocm5.1.1".pip.packages]
torch = "1.12.0+rocm5.1.1"
torchvision = "0.13.0+rocm5.1.1"
torchaudio = "0.12.0"

[["rocm5.2".pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/rocm5.2"]
version = "1.13.1"
platform = "rocm5.2"

["rocm5.2".pip.packages]
torch = "1.13.1+rocm5.2"
torchvision = "0.14.1+rocm5.2"
torchaudio = "0.13.1"

[["rocm5.2".pip]]
installer = "pip"
flags = ["--extra-index-url", "https://download.pytorch.org/whl/rocm5.2"]
version = "1.13.0"
platform = "rocm5.2"

["rocm5.2".pip.packages]
torch = "1.13.0+rocm5.2"
torchvision = "0.14.0+rocm5.2"
torchaudio = "0.13.0"

[["rocm5.4.2".pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/rocm5.4.2",
]
platform = "rocm5.4.2"
version = "latest"

["rocm5.4.2".pip.packages]

[["rocm5.4.2".pip]]
installer = "pip"
flags = ["--index-url", "https://download.pytorch.org/whl/rocm5.4.2"]
version = "2.0.0"
platform = "rocm5.4.2"

["rocm5.4.2".pip.packages]
torch = "2.0.0+rocm5.4.2"
torchvision = "0.15.1"
torchaudio = "2.0.1"

[["rocm5.6".pip]]
installer = "pip"
flags = [
  "torch",
  "torchvision",
  "torchaudio",
  "--index-url",
  "https://download.pytorch.org/whl/rocm5.6",
]
platform = "rocm5.6"
version = "latest"

["rocm5.6".pip.packages]
